version: "3.8"
services:
  frontend:
    build:
      context: ./smoothSearch
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    image: frontend:react
    container_name: smoothSearch
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    image: backend:node
    container_name: backend
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true